### PR TITLE
Smaller epsilon for points

### PR DESCRIPTION
**Pull request by tapir**

### CODE REVIEW

**Comment by tapir** [comment]
@kaadmy could you test this with your maps. From my tests, it looks like it doesn't mess up anything but more eyes the better

**Comment by jdolan** [comment]
Gehenna and Wake would be good test cases for this.

**Comment by jdolan** [comment]
Did some testing with this. Massive improvements on Jester's crazy complex geometry.

@Panjoo can you think of any existing maps that have brush errors (cracks between faces, etc) that would benefit from a recompile?

Awesome find and fix @tapir.

**Comment by jdolan** [comment]
Gehenna could definitely use a recompile. The self-jerking-off pipes in the main atrium have numerous small brush errors.

**Comment by kaadmy** [comment]
What exactly does this fix?

**Comment by tapir** [comment]
fixing missing narrow surfaces in jgothic and gevennah

**Pull request merged**
